"""Generates ``GMBank_data.generated.h`` from a fully resolved
:class:`~ctsb_converter.model.GMBankData`.

Only immutable ``constexpr`` data is emitted; no C++ logic, no SF2
vocabulary. The runtime firmware (handwritten ``GMBank.h``/``GMBank.cpp``)
declares the companion types and simply ``#include``s this file.
"""

from __future__ import annotations

import struct
from pathlib import Path
from typing import Iterable, List

from .model import GMBankData, MELODIC_INSTRUMENT_COUNT, PERCUSSION_BANK, RUNTIME_SAMPLE_RATE_HZ

_PCM_VALUES_PER_LINE = 16
_HEADER_GUARD = "CTSB_GM_BANK_GENERATED_H"


def _escape_string(text: str) -> str:
    escaped = text.replace("\\", "\\\\").replace('"', '\\"')
    # Keep the generated header pure ASCII; non-printable/non-ASCII sample
    # or preset names become '?' rather than risking encoding issues.
    return "".join(ch if 32 <= ord(ch) < 127 else "?" for ch in escaped)


def _format_sample_entry(entry, index: int) -> str:
    return (
        f"    /* [{index}] */ {{ {entry.pcm_offset}u, {entry.length}u, {entry.loop_start}u, "
        f"{entry.loop_end}u, {entry.root_note}u, {entry.fine_tune}, {entry.flags}u }},"
    )


def _format_pcm_data(pcm: bytes) -> Iterable[str]:
    count = len(pcm) // 2
    values = struct.unpack(f"<{count}h", pcm) if count else ()
    for i in range(0, len(values), _PCM_VALUES_PER_LINE):
        chunk = values[i : i + _PCM_VALUES_PER_LINE]
        yield "    " + ", ".join(str(v) for v in chunk) + ","


def _format_lookup_row(row: List[int]) -> str:
    return "    { " + ", ".join(str(v) for v in row) + " },"


def _format_preset(preset) -> str:
    name = _escape_string(preset.name)
    return f'    {{ "{name}", {preset.instrument_index}u, {preset.bank}u, {preset.preset}u }},'


def generate_header(bank: GMBankData) -> str:
    lines: List[str] = []
    lines.append("// AUTO-GENERATED FILE - DO NOT EDIT.")
    lines.append("// Generated by tools/sf2converter (cTSB Converter).")
    lines.append("//")
    lines.append("// Expected companion declarations (handwritten GMBank.h):")
    lines.append("//   struct SampleEntry {")
    lines.append("//     uint32_t pcmOffset, length, loopStart, loopEnd;")
    lines.append("//     uint8_t rootNote; int8_t fineTune; uint16_t flags;")
    lines.append("//   };")
    lines.append('//   struct PresetInfo { const char *name; uint16_t instrumentIndex; uint8_t bank; uint8_t preset; };')
    lines.append("//")
    lines.append(f"// Runtime PCM sample rate is fixed at {RUNTIME_SAMPLE_RATE_HZ} Hz for all entries.")
    lines.append(f"#ifndef {_HEADER_GUARD}")
    lines.append(f"#define {_HEADER_GUARD}")
    lines.append("")
    lines.append("#include <cstdint>")
    lines.append("")
    lines.append(f"constexpr uint16_t kGMInstrumentCount = {bank.instrument_count}u;")
    lines.append(f"constexpr uint16_t kGMSampleEntryCount = {len(bank.sample_entries)}u;")
    lines.append(f"constexpr uint32_t kGMPcmSampleCount = {len(bank.pcm_data) // 2}u;")
    lines.append(f"constexpr uint16_t kGMPresetCount = {len(bank.presets)}u;")
    lines.append("")

    lines.append("constexpr SampleEntry sampleEntries[] = {")
    for i, entry in enumerate(bank.sample_entries):
        lines.append(_format_sample_entry(entry, i))
    lines.append("};")
    lines.append("")

    lookup_rows = len(bank.lookup)
    lines.append(f"constexpr uint16_t sampleLookup[{lookup_rows}][128] = {{")
    for row in bank.lookup:
        lines.append(_format_lookup_row(row))
    lines.append("};")
    lines.append("")

    lines.append("constexpr int16_t pcmData[] = {")
    lines.extend(_format_pcm_data(bank.pcm_data))
    if not bank.pcm_data:
        lines.append("    0,")
    lines.append("};")
    lines.append("")

    lines.append("constexpr PresetInfo presets[] = {")
    for preset in bank.presets:
        lines.append(_format_preset(preset))
    if not bank.presets:
        lines.append('    { "", 0u, 0u, 0u },')
    lines.append("};")
    lines.append("")

    lines.append(f"#endif // {_HEADER_GUARD}")
    lines.append("")
    return "\n".join(lines)


def write_header(bank: GMBankData, output_directory: Path) -> Path:
    output_directory.mkdir(parents=True, exist_ok=True)
    output_path = output_directory / "GMBank_data.generated.h"
    output_path.write_text(generate_header(bank), encoding="ascii")
    return output_path
