/*
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Copyright (c) 2018 Discodirt
 * Copyright (c) 2024 xiphonics, inc.
 * Copyright (c) 2026 nILS Podewski
 *
 * This file was part of the picoTracker firmware
 * This file is part of the copingTracker firmware
 */

#ifndef _RANDOMNAMES_H_
#define _RANDOMNAMES_H_

#include "System/System/System.h"
#include <string.h>

static const char *adjectives[] = {"glow", "soft", "snug", "tiny", "tofu", "lofi", "bree", "drip", "zany", "wavy",
                                   "bork", "puff", "noiz", "crux", "kute", "mild", "wild", "blep", "loud", "mute",
                                   "cold", "warm", "dank", "sick", "fuzz", "vibe", "warp", "ping", "pong", "chip",
                                   "glit", "bzzz", "plop", "zoop", "meep", "boop", "red",  "gray"};

static const char *verbs[] = {"bit", "zip", "zap", "tap", "pop", "mux", "bus", "ram", "rom", "osc", "dac", "adc", "vox", "sfx",
                              "mod", "cpu", "gpu", "pad", "seq", "run", "sum", "jam", "wig", "bun", "cat", "dog", "fox", "bee",
                              "cow", "pig", "ant", "owl", "rat", "bat", "cod", "yak", "emu", "eel", "pig", "yak", "ape", "ape",
                              "bat", "rat", "bug", "fly", "mop", "ink", "oil", "gas", "ice", "ash", "mud", "fog", "sun", "sky",
                              "sea", "sky", "ice", "mud", "log", "pit", "pit", "jam", "jam", "zap", "zap"};

// Generate a name made in the format of: "adjective-verb"
// chosen from small word lists of words 3-4 chars in length
// based on the index number passed in, normally this will have been randomly
// generated by the caller eg. "fast-sea", "wet-pea", "mad-paw" etc
void getRandomName(char *name, size_t nameSize);

#endif
