#!/usr/bin/env python3

import argparse
import math
from pathlib import Path


DEFAULT_TABLE_SIZE = 2048
HARMONIC_LIMITS = (256, 128, 64, 32, 16, 8, 4)

INT16_MAX = 32767
INT16_MIN = -32768


def normalize(samples):
    peak = max(abs(x) for x in samples)

    if peak == 0:
        return [0] * len(samples)

    scale = INT16_MAX / peak

    return [
        max(INT16_MIN, min(INT16_MAX, round(x * scale)))
        for x in samples
    ]


def additive_table(table_size, components):
    table = [0.0] * table_size

    for harmonic, amplitude, phase in components:
        phase_step = 2.0 * math.pi * harmonic / table_size

        for i in range(table_size):
            table[i] += amplitude * math.sin(
                phase_step * i + phase
            )

    return normalize(table)


def saw(table_size, max_harmonic):
    components = []

    for n in range(1, max_harmonic + 1):
        amplitude = (1.0 if n & 1 else -1.0) / n
        components.append((n, amplitude, 0.0))

    return additive_table(table_size, components)


def triangle(table_size, max_harmonic):
    components = []

    for n in range(1, max_harmonic + 1, 2):
        k = (n - 1) // 2
        amplitude = (1.0 if k % 2 == 0 else -1.0) / (n * n)
        components.append((n, amplitude, 0.0))

    return additive_table(table_size, components)


def pulse(table_size, max_harmonic, duty):
    components = []

    for n in range(1, max_harmonic + 1):
        amplitude = 2.0 * math.sin(math.pi * n * duty) / n
        phase = -math.pi * n * duty

        components.append((n, amplitude, phase))

    return additive_table(table_size, components)


def organ_hammond(table_size, max_harmonic):
    """
    Approximate Hammond drawbar spectrum.
    """

    drawbars = {
        1: 1.00,   # 16'
        2: 0.80,   # 8'
        3: 0.55,   # 5 1/3'
        4: 0.35,   # 4'
        5: 0.20,   # 2 2/3'
        6: 0.28,   # 2'
        8: 0.15,   # 1'
        10: 0.08,
        12: 0.06,
        16: 0.04,
    }

    components = [
        (n, amplitude, 0.0)
        for n, amplitude in drawbars.items()
        if n <= max_harmonic
    ]

    return additive_table(table_size, components)


def vox_ah(table_size, max_harmonic):
    """
    Rough synthetic "AH" vowel spectrum.
    """

    harmonics = {
        1: 1.00,
        2: 0.18,
        3: 0.78,
        4: 0.10,
        5: 0.55,
        6: 0.12,
        7: 0.38,
        8: 0.08,
        9: 0.24,
        10: 0.06,
        11: 0.16,
        12: 0.04,
        13: 0.10,
        14: 0.03,
        15: 0.07,
        16: 0.02,
    }

    components = [
        (n, amplitude, 0.0)
        for n, amplitude in harmonics.items()
        if n <= max_harmonic
    ]

    return additive_table(table_size, components)


WAVEFORMS = {
    "pulse12_5": lambda size, h: pulse(size, h, 0.125),
    "pulse25": lambda size, h: pulse(size, h, 0.25),
    "pulse50": lambda size, h: pulse(size, h, 0.50),
    "saw": saw,
    "triangle": triangle,
    "organ_hammond": organ_hammond,
    "vox_ah": vox_ah,
}


def c_identifier(name):
    return name.replace("-", "_").replace(".", "_")


def write_array(f, name, samples):
    f.write(
        f"alignas(4) static constexpr int16_t "
        f"{name}[{len(samples)}] = {{\n"
    )

    for i in range(0, len(samples), 16):
        values = samples[i:i + 16]

        f.write("    ")
        f.write(", ".join(f"{x:6d}" for x in values))
        f.write(",\n")

    f.write("};\n\n")


def write_table_pointer_array(f, name, prefix):
    f.write(
        f"static constexpr const int16_t *{name}"
        f"[MIP_LEVELS] = {{\n"
    )

    for level in range(len(HARMONIC_LIMITS)):
        f.write(f"    {prefix}_{level},\n")

    f.write("};\n\n")


def generate(table_size, output_path):
    output = Path(output_path)

    with output.open("w", encoding="utf-8") as f:
        f.write("""// Generated by generate_stack_wavetables.py
// Do not edit manually.

#pragma once

#include <stdint.h>
#include <stddef.h>

namespace StackWavetables
{

""")

        f.write(
            f"static constexpr size_t TABLE_SIZE = {table_size};\n"
        )

        f.write(
            f"static constexpr size_t MIP_LEVELS = "
            f"{len(HARMONIC_LIMITS)};\n\n"
        )

        f.write(
            "static constexpr uint16_t MAX_HARMONICS[MIP_LEVELS] = {\n"
        )
        f.write(
            "    " + ", ".join(map(str, HARMONIC_LIMITS)) + "\n"
        )
        f.write("};\n\n")

        # Generate individual wavetable arrays.
        for wave_name, generator in WAVEFORMS.items():
            prefix = f"WT_{c_identifier(wave_name).upper()}"

            for level, harmonic_limit in enumerate(HARMONIC_LIMITS):
                samples = generator(
                    table_size,
                    harmonic_limit
                )

                write_array(
                    f,
                    f"{prefix}_{level}",
                    samples
                )

        # Generate one pointer array for each waveform.
        for wave_name in WAVEFORMS:
            identifier = c_identifier(wave_name)
            prefix = f"WT_{identifier.upper()}"

            write_table_pointer_array(
                f,
                f"{identifier}_tables",
                prefix
            )

        # Generate a master array containing all waveform arrays.
        f.write(
            "static constexpr const int16_t *const *"
            "stack_wavetables[] = {\n"
        )

        for wave_name in WAVEFORMS:
            identifier = c_identifier(wave_name)
            f.write(f"    {identifier}_tables,\n")

        f.write("};\n\n")

        f.write(
            "static constexpr size_t WAVEFORM_COUNT = "
            "sizeof(stack_wavetables) / "
            "sizeof(stack_wavetables[0]);\n\n"
        )

        # Waveform enum.
        f.write("enum Wave : uint8_t\n{\n")

        for index, wave_name in enumerate(WAVEFORMS):
            f.write(
                f"    {c_identifier(wave_name).upper()} = {index},\n"
            )

        f.write("};\n\n")

        f.write("} // namespace StackWavetables\n")

    total_bytes = (
        table_size
        * len(HARMONIC_LIMITS)
        * len(WAVEFORMS)
        * 2
    )

    print(f"Generated {output}")
    print(f"  table size : {table_size}")
    print(f"  mip levels : {len(HARMONIC_LIMITS)}")
    print(f"  harmonics  : {HARMONIC_LIMITS}")
    print(f"  waveforms  : {len(WAVEFORMS)}")
    print(f"  total data : {total_bytes / 1024:.1f} KiB")


def main():
    parser = argparse.ArgumentParser(
        usage="%(prog)s <output.h> [--table-size N]"
    )

    parser.add_argument(
        "output",
        nargs="?",
        help="Output C++ header path"
    )

    parser.add_argument(
        "--table-size",
        type=int,
        default=DEFAULT_TABLE_SIZE,
        help="Samples per table (default: 2048)"
    )

    args = parser.parse_args()

    if args.output is None:
        print(
            f"Usage: {parser.prog} <output.h> [--table-size N]"
        )
        return 1

    if (
        args.table_size < 16
        or (args.table_size & (args.table_size - 1))
    ):
        parser.error(
            "--table-size must be a power of two >= 16"
        )

    generate(args.table_size, args.output)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())